"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['icons/Menu_icon.png', 'icons/App_icon.icns', 'rump.py', '.env', 'chatbox_WEB.py', 'enter_api_WEB.py', 'langchain_functions.py']
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': 'Majid',
        'CFBundleDisplayName': 'Majid',
        'CFBundleIconFile': 'App_icon.icns'  # <- this tells macOS which icon to use
    },
    'packages': [],
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
